name: 'Bump Version'

on:
  push:
    branches:
      - 'master_2'

jobs:
  bump-version:
    name: 'Bump Version on master'
    runs-on: ubuntu-18.04

    steps:
      - name: 'Checkout source code'
        uses: 'actions/checkout@v2'
        with:
          ref: ${{ github.ref }}
      - name: 'cat package.json'
        run: cat ./package.json
      - name: banana
        run: node -e "console.log(process.env.AAA)"
        env:
          AAA: ${{ secrets.GH_ACTION_TOKEN }}
      - name: 'Automated Version Bump'
        id: version-bump
        uses: 'phips28/gh-action-bump-version@v9.0.1'
        with:
          tag-prefix: 'v2-'
          commit-message: 'Bumps version to {{version}}'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACTION_TOKEN }}
      - name: 'cat package.json'
        run: cat ./package.json
      - name: 'Output Stepa'
        env:
          NEW_TAG: ${{ steps.version-bump.outputs.newTag }}
        run: echo "new tag $NEW_TAG"
